### importing required packages

In [2]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\dongr\anaconda3\lib\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\dongr\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\dongr\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\dongr\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\dongr\anaconda3\lib\site-packages (from mlxtend) (1.7.0)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\dongr\anaconda3\lib\site-packages (from mlxtend) (3.8.4)
Requirement already satisfied: joblib>=0.13.2 in c:\users\dongr\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dongr\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\dongr\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dongr\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\dongr\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\dongr\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\dongr\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dongr\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\dongr\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dongr\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dongr\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\dongr\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dongr\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)

In [4]:
#importing required libraries
import pandas as pd 
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [5]:
#importing warings 
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
data = pd.read_excel('Online retail.xlsx')

In [6]:
print(data.shape) #which tells about no of rows and no of columns
data.head()# which tells about first few number of rows data

(7500, 20)

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In this dataset we have alot of null or missing values so here is a need of data preprocessing

In [9]:
df=pd.DataFrame(data) #converting our data to a dataframe

In [10]:
print(df.isnull().sum()) #printing or checking null values are ther or not and if there are null then printing the sum of those

shrimp                  0
almonds              1754
avocado              3112
vegetables mix       4156
green grapes         4972
whole weat flour     5637
yams                 6132
cottage cheese       6520
energy drink         6847
tomato juice         7106
low fat yogurt       7245
green tea            7347
honey                7414
salad                7454
mineral water        7476
salmon               7493
antioxydant juice    7497
frozen smoothie      7497
spinach              7498
olive oil            7500
dtype: int64

In [11]:
data.fillna(0,inplace=True) #replacing null values

In [12]:
df.dtypes #checking data types

shrimp                object
almonds               object
avocado               object
vegetables mix        object
green grapes          object
whole weat flour      object
yams                  object
cottage cheese        object
energy drink          object
tomato juice          object
low fat yogurt        object
green tea             object
honey                 object
salad                 object
mineral water         object
salmon                object
antioxydant juice     object
frozen smoothie       object
spinach               object
olive oil            float64
dtype: object

### Data Preproccesing

In [20]:
df.drop_duplicates() #removing any duplicate values if present and printing  new dataframe

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,burgers,meatballs,eggs,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
1,chutney,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
2,turkey,avocado,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
3,mineral water,milk,energy bar,whole wheat rice,green tea,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
4,low fat yogurt,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7492,burgers,salmon,pancakes,french fries,frozen smoothie,fresh bread,mint,0,0,0,0,0,0,0,0,0,0,0,0,0.0
7493,turkey,burgers,dessert wine,shrimp,pasta,tomatoes,pepper,milk,pancakes,whole wheat rice,oil,frozen smoothie,0,0,0,0,0,0,0,0.0
7495,butter,light mayo,fresh bread,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0

### using Apriori algorithms for associations finding

our dataset is in the form of obeject so we have to transform it into one hot encodeded data frame

In [24]:
data = [[str(item) for item in transaction] for transaction in data]

# Now applying the TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)

# Applying the Apriori algorithm
frequent_itemsets = apriori(df, min_support=0.1, use_colnames=True)

# Displaying the frequent itemsets
print(frequent_itemsets)

      support                     itemsets
0        0.60                          ( )
1        0.75                          (a)
2        0.25                          (c)
3        0.25                          (d)
4        0.60                          (e)
...       ...                          ...
1771     0.10     (u, f, r, t,  , w, l, o)
1772     0.10     (u, c, a, i, t, j, e, o)
1773     0.10     (u, f, a, r, t, w, l, o)
1774     0.10  (u, c, a, i, t,  , j, e, o)
1775     0.10  (u, f, a, r, t,  , w, l, o)

[1776 rows x 2 columns]

In [26]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,( ),(a),0.60,0.75,0.45,0.750000,1.000000,1.0,5.551115e-17,1.000000,3.083953e-16,0.500000,0.000000,0.675000
1,(a),( ),0.75,0.60,0.45,0.600000,1.000000,1.0,5.551115e-17,1.000000,4.934325e-16,0.500000,0.000000,0.675000
2,( ),(c),0.60,0.25,0.15,0.250000,1.000000,1.0,0.000000e+00,1.000000,0.000000e+00,0.214286,0.000000,0.425000
3,(c),( ),0.25,0.60,0.15,0.600000,1.000000,1.0,0.000000e+00,1.000000,0.000000e+00,0.214286,0.000000,0.425000
4,( ),(e),0.60,0.60,0.55,0.916667,1.527778,1.0,1.900000e-01,4.800000,8.636364e-01,0.846154,0.791667,0.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48613,(t),"(u, f, a, r, , w, l, o)",0.45,0.10,0.10,0.222222,2.222222,1.0,5.500000e-02,1.157143,1.000000e+00,0.222222,0.135802,0.611111
48614,( ),"(u, f, a, r, t, w, l, o)",0.60,0.10,0.10,0.166667,1.666667,1.0,4.000000e-02,1.080000,1.000000e+00,0.166667,0.074074,0.583333
48615,(w),"(u, f, a, r, t, , l, o)",0.15,0.10,0.10,0.666667,6.666667,1.0,8.500000e-02,2.700000,1.000000e+00,0.666667,0.629630,0.833333
48616,(l),"(u, f, a, r, t, , w, o)",0.40,0.10,0.10,0.250000,2.500000,1.0,6.000000e-02,1.200000,1.000000e+00,0.250000,0.166667,0.625000
48617,(o),"(u, f, a, r, t, , w, l)",0.55,0.10,0.10,0.181818,1.818182,1.0,4.500000e-02,1.100000,1.000000e+00,0.181818,0.090909,0.590909

In [27]:
rules.sort_values('lift',ascending = False)[0:20]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
24309,"(f, a, )","(u, r, t)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28639,"(u, r, t)","(l, f, )",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
7061,"(u, c)","(j, i)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
7062,"(u, i)","(j, c)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
7063,"(j, c)","(u, i)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
7064,"(j, i)","(u, c)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
7067,(j),"(u, c, i)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28640,"(u, , r)","(t, f, l)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28633,"(t, f, l, )","(u, r)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28592,"(l, w, o)","(u, f, )",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28626,"(u, , r, t)","(l, f)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28606,"(w, o)","(u, f, l, )",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28600,"(l, f)","(u, , w, o)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28599,"(f, w)","(u, , l, o)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28596,"(u, l)","(f, w, , o)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28595,"(u, w)","(l, f, , o)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
7058,"(u, c, i)",(j),0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28649,"(t, f, l)","(u, , r)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
28650,"(l, f, )","(u, r, t)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0
7053,(j),"(t, c, i)",0.1,0.1,0.1,1.0,10.0,1.0,0.09,inf,1.0,1.0,1.0,1.0

In [30]:
rules[rules.lift>2]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
62,(j),(c),0.10,0.25,0.10,1.000000,4.000000,1.0,0.075,inf,0.833333,0.400000,1.000000,0.700000
63,(c),(j),0.25,0.10,0.10,0.400000,4.000000,1.0,0.075,1.500000,1.000000,0.400000,0.333333,0.700000
106,(f),(h),0.15,0.30,0.10,0.666667,2.222222,1.0,0.055,2.100000,0.647059,0.285714,0.523810,0.500000
107,(h),(f),0.30,0.15,0.10,0.333333,2.222222,1.0,0.055,1.275000,0.785714,0.285714,0.215686,0.500000
112,(f),(r),0.15,0.40,0.15,1.000000,2.500000,1.0,0.090,inf,0.705882,0.375000,1.000000,0.687500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48610,(f),"(u, a, r, t, , w, l, o)",0.15,0.10,0.10,0.666667,6.666667,1.0,0.085,2.700000,1.000000,0.666667,0.629630,0.833333
48612,(r),"(u, f, a, t, , w, l, o)",0.40,0.10,0.10,0.250000,2.500000,1.0,0.060,1.200000,1.000000,0.250000,0.166667,0.625000
48613,(t),"(u, f, a, r, , w, l, o)",0.45,0.10,0.10,0.222222,2.222222,1.0,0.055,1.157143,1.000000,0.222222,0.135802,0.611111
48615,(w),"(u, f, a, r, t, , l, o)",0.15,0.10,0.10,0.666667,6.666667,1.0,0.085,2.700000,1.000000,0.666667,0.629630,0.833333
48616,(l),"(u, f, a, r, t, , w, o)",0.40,0.10,0.10,0.250000,2.500000,1.0,0.060,1.200000,1.000000,0.250000,0.166667,0.625000

### Interpretation 
Items such as (chocolate), (eggs), (french fries), (milk), and (spaghetti) have notable support values, indicating they are commonly purchased by customers.Many antecedents have a support close to 1 (e.g., (nan)), indicating that they appear in almost all transactions. This suggests that these items are very common in the dataset, possibly indicating frequent purchases or default values.

The confidence values for rules involving (nan) as antecedents are very high (close to 1), which implies that when these items are present, the likelihood of the consequent being purchased is also very high.

The lift values are slightly above 1, suggesting that the presence of the antecedents does lead to a higher likelihood of purchasing the consequents than would be expected by chance

Overall, the analysis highlights significant purchasing patterns among the items, which can be valuable for marketing strategies, inventory management, and understanding customer behavior..

### Interview Questions

 #### 1. What is Lift and Why is it Important in Association Rules?
Lift is a measure used in association rule mining to evaluate the strength of a rule. It compares the observed support of the rule with the expected support if the antecedent and consequent were independent.

Calculation of Lift:

Lift (A → B) = Support(A and B) /  Support(A) * Support(B)

Support(A and B): The proportion of transactions that contain both the antecedent (A) and the consequent (B).

Support(A): The proportion of transactions that contain the antecedent (A).

Support(B): The proportion of transactions that contain the consequent (B).


Importance of Lift:

Lift is an important metric that helps us understand how products relate to each other in terms of purchasing behavior. It tells us how much more likely a customer is to buy a particular item (the consequent) when they’ve already chosen another item (the antecedent), compared to when those items are bought independently. If the lift value is greater than 1, it indicates a positive connection, meaning customers tend to buy those items together. Conversely, a lift value less than 1 suggests they are less likely to be purchased together. By identifying these strong associations, businesses can develop smarter marketing strategies, such as cross-selling and targeted promotions, which can lead to increased customer satisfaction and higher sales.

#### 2. What are Support and Confidence? How Do You Calculate Them?
Support and Confidence are two fundamental metrics in association rule mining.

Support:
•	Definition: Support measures the proportion of transactions in the dataset that contain a specific itemset (both antecedent and consequent).

•	Calculation: Support(A)=Number of transactions containing ATotal number of transactionsSupport(A)=Total number of transactionsNumber of transactions containing A

•	Example: If 100 transactions contain chocolate, and there are 1000 total transactions, the support for chocolate is 0.10.1 or 10%10%.

Confidence:

•	Definition: Confidence measures the likelihood that the consequent is purchased when the antecedent is present. It indicates the strength of the implication of the rule.

•	Calculation:
 Confidence(A → B) = Support(A and B) / Support (A)

•	Example: If 30 transactions contain both chocolate and milk, and 100 transactions contain chocolate, the confidence of the rule "If chocolate, then milk" is 0.30.3 or 30%30%.


#### 3. What Are Some Limitations or Challenges of Association Rules Mining?
While association rule mining is a powerful technique, it does have several limitations and challenges:

1.	Large Dataset Requirements:
•	Association rule mining can be computationally intensive, especially with large datasets. The number of possible itemsets grows exponentially with the number of items, leading to significant processing time and resource consumption.

2.	Interpretability:
•	The rules generated can sometimes be difficult to interpret, especially if they involve many items or if the support and confidence values are low. Users may struggle to derive actionable insights from complex rules.

3.	Data Quality Issues:
•	The presence of missing values, noise, or irrelevant items in the dataset can lead to misleading results. Proper data cleaning and preprocessing are essential to ensure meaningful analysis.

4.	Overfitting:
•	There is a risk of generating too many rules, some of which may not be practically useful. This can lead to overfitting, where the model captures noise rather than true patterns.

The choice of support and confidence thresholds can significantly affect the results. Setting these thresholds too high may lead to missing important associations, while setting them too low may result in too many trivial rules.